### ISSUE TITLE
Error: Non-zero status code

### ISSUE THREAD

**Issue by winktool** [Hyuto/yolov5-seg-onnxruntime-web#2]
```
2023-02-15 15:11:16.955 node[23290:358292] 2023-02-15 15:11:16.955568 [E:onnxruntime:, sequential_executor.cc:369 Execute] Non-zero status code returned while running MatMul node. Name:'onnx_graphsurgeon_node_125' Status Message: matmul_helper.h:61 Compute MatMul dimension mismatch
```
Maybe in 
```

      const { mask_filter } = await session.mask.run({
        detection: mask,
        mask: output1,
        config: maskConfig,
      }); // get mask
      
      ```

**Comment by winktool** [comment]
When i used the ```yolov5x-seg.onnx```, i got ```Error: Can't create a session``` error.Maybe the reason is that i must use the onnx model base on ```yolov5n-seg.onnx```.

**Comment by winktool** [comment]
I used ```python segment/predict.py --weights /home/Project/yolov5/runs/train-seg/exp5/weights/best.pt --source 1655573290329_jpg.rf.6a611bd8e82b6061d5f463ac364fb984.jpg``` get the wright answer.SO my model is ok.

**Comment by winktool** [comment]
```
(yolov5) xxx@desktop:~/Project/yolov5$ python export.py --data data/bicycle.yaml  --weights /home/Project/yolov5/runs/train-seg/exp5/weights/best.pt --include onnx --img 640 --opset 12
export: data=data/bicycle.yaml, weights=['/home/Project/yolov5/runs/train-seg/exp5/weights/best.pt'], imgsz=[640], batch_size=1, device=cpu, half=False, inplace=False, keras=False, optimize=False, int8=False, dynamic=False, simplify=False, opset=12, verbose=False, workspace=4, nms=False, agnostic_nms=False, topk_per_class=100, topk_all=100, iou_thres=0.45, conf_thres=0.25, include=['onnx']
YOLOv5 🚀 v7.0-62-g37d1e5e Python-3.8.10 torch-1.8.1+cu102 CPU

Fusing layers... 
Model summary: 330 layers, 88242854 parameters, 0 gradients, 264.0 GFLOPs

PyTorch: starting from /home/Project/yolov5/runs/train-seg/exp5/weights/best.pt with output shape (1, 25200, 38) (169.0 MB)

ONNX: starting export with onnx 1.12.0...
ONNX: export success ✅ 8.8s, saved as /home/Project/yolov5/runs/train-seg/exp5/weights/best.onnx (337.1 MB)

Export complete (13.1s)
Results saved to /home/Project/yolov5/runs/train-seg/exp5/weights
Detect:          python segment/predict.py --weights /home/Project/yolov5/runs/train-seg/exp5/weights/best.onnx 
Validate:        python segment/val.py --weights /home/Project/yolov5/runs/train-seg/exp5/weights/best.onnx 
PyTorch Hub:     model = torch.hub.load('ultralytics/yolov5', 'custom', '/home/Project/yolov5/runs/train-seg/exp5/weights/best.onnx')  # WARNING ⚠️ SegmentationModel not yet supported for PyTorch Hub AutoShape inference
Visualize:       https://netron.app
```

**Comment by Hyuto** [comment]
> ```
> (yolov5) xxx@desktop:~/Project/yolov5$ python export.py --data data/bicycle.yaml  --weights /home/Project/yolov5/runs/train-seg/exp5/weights/best.pt --include onnx --img 640 --opset 12
> export: data=data/bicycle.yaml, weights=['/home/Project/yolov5/runs/train-seg/exp5/weights/best.pt'], imgsz=[640], batch_size=1, device=cpu, half=False, inplace=False, keras=False, optimize=False, int8=False, dynamic=False, simplify=False, opset=12, verbose=False, workspace=4, nms=False, agnostic_nms=False, topk_per_class=100, topk_all=100, iou_thres=0.45, conf_thres=0.25, include=['onnx']
> YOLOv5 🚀 v7.0-62-g37d1e5e Python-3.8.10 torch-1.8.1+cu102 CPU
> 
> Fusing layers... 
> Model summary: 330 layers, 88242854 parameters, 0 gradients, 264.0 GFLOPs
> 
> PyTorch: starting from /home/Project/yolov5/runs/train-seg/exp5/weights/best.pt with output shape (1, 25200, 38) (169.0 MB)
> 
> ONNX: starting export with onnx 1.12.0...
> ONNX: export success ✅ 8.8s, saved as /home/Project/yolov5/runs/train-seg/exp5/weights/best.onnx (337.1 MB)
> 
> Export complete (13.1s)
> Results saved to /home/Project/yolov5/runs/train-seg/exp5/weights
> Detect:          python segment/predict.py --weights /home/Project/yolov5/runs/train-seg/exp5/weights/best.onnx 
> Validate:        python segment/val.py --weights /home/Project/yolov5/runs/train-seg/exp5/weights/best.onnx 
> PyTorch Hub:     model = torch.hub.load('ultralytics/yolov5', 'custom', '/home/Project/yolov5/runs/train-seg/exp5/weights/best.onnx')  # WARNING ⚠️ SegmentationModel not yet supported for PyTorch Hub AutoShape inference
> Visualize:       https://netron.app
> ```

Can you let me access your custom model and it's label for testing purpose?

**Comment by winktool** [comment]
Thank you for your reply, of course!

**Comment by winktool** [comment]
I am uploading, please wait

**Comment by winktool** [comment]
I have sent a link to the file to your email address ```wahyusetianto19@gmail.com```.

**Comment by Hyuto** [comment]
Hello, just a little update here. The latest commit is now supported for custom trained YOLOv5 Segmentation model. You just have to update `src/utils/labels.json` with your model classes.

**Comment by winktool** [comment]
You are great!

**Comment by Hyuto** [comment]
Thank you. If there is no problem left, I'm closing this issue.
